# Change these first
owner: JRAM05 # Your GitHub organization or username, where this repository lives
repo: status_services # The name of this repository
  
Skip delete issues: true
  
sites:
- name: E4CC
  url: $Main_Site
  icon: https://e4ccsv.com/Uploads/Img/ms-icon-70x70.png
  maxResponseTime: 5000
  delay: 5000
  expectedStatusCodes:
  - 200   # OK, la solicitud ha tenido éxito
  - 400   # Bad Request, solicitud incorrecta
  - 403   # Forbidden, no autorizado
  - 404   # Not Found, recurso no encontrado
  - 500   # Internal Server Error, error interno del servidor
  - 502   # Bad Gateway, respuesta no válida del servidor ascendente
  - 503   # Service Unavailable, servidor no disponible
- name: Portal Coach
  url: $Second_Site 
  icon: https://e4ccsv.com/Uploads/Img/ms-icon-70x70.png
  maxResponseTime: 5000
  delay: 5000
  expectedStatusCodes:
  - 200   # OK, la solicitud ha tenido éxito
  - 400   # Bad Request, solicitud incorrecta
  - 403   # Forbidden, no autorizado
  - 404   # Not Found, recurso no encontrado
  - 500   # Internal Server Error, error interno del servidor
  - 502   # Bad Gateway, respuesta no válida del servidor ascendente
  - 503   # Service Unavailable, servidor no disponible
  
assignees:
  - JRAM05

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status_services
  favicon: https://e4ccsv.com/Uploads/Img/ms-icon-70x70.png
  logoUrl: https://e4ccsv.com/Uploads/Img/ms-icon-70x70.png
  name: Status Page
  introTitle: "**E4CC Status Page** - Monitoreo en tiempo real de nuestros servicios"
  introMessage: "Bienvenido a la página de estado de **E4CC**. Aquí puedes verificar la disponibilidad y el rendimiento de nuestros servicios en **tiempo real**. Nuestro sistema se actualiza automáticamente para brindarte información precisa y transparente. Si experimentas problemas que no aparecen aquí, por favor contacta a nuestro equipo de soporte."
  description: "Monitoreo en tiempo real de los servicios de E4CC."
  robotsText: |
    User-agent: *
    Disallow: /
  navbar:
    - title: E4CC
      href: $Main_Site
    - title: Portal Coach
      href: $Second_Site 
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
